
/* test3d.h	   Created:    1993-12-21  Revised:    1994-05-30	*/

/* PMCX	Control	Example	Constants Header				*/

/* Copyright ¸ 1989-1996  Prominare Inc.  All Rights Reserved.		*/


#define	TS_DEPRESSED	  0x0000L
#define	TS_RAISED	  0x0100L

#define	DS_DEPRESSED	  0x0000L
#define	DS_RAISED	  0x0040L

/* --- Miscellaneous Constants ----------------------------------------	*/

#define	DID_HELP	      3	   /* Help Push	Button ID		*/
#define	DID_FONTCLR	     11	   /* Font & Colour Push Button	ID	*/
#define	DID_BIDI	     12	   /* Bidi Push	Button ID		*/

#define	CB_VISIBLE	    256	   /* Visible Check Box	ID		*/
#define	CB_GROUP	    257	   /* Group Check Box ID		*/
#define	CB_DISABLED	    258	   /* Disabled Check Box ID		*/
#define	CB_TABSTOP	    259	   /* Tab Stop Check Box ID		*/

#define	IDS_VISIBLE	    512	   /* Visible Style String		*/
#define	IDS_GROUP	    513	   /* Group Style String		*/
#define	IDS_DISABLED	    514	   /* Disabled Style String		*/
#define	IDS_TABSTOP	    515	   /* Tab Stop Style String		*/

/* --- Control Dialogue	-----------------------------------------------	*/

#define	DLG_CTRLUSER	   1000	   /* User Defined Dialog		*/
#define	RB_LEFTALIGNED	   4042	   /* Left Aligned Radio Button		*/
#define	RB_HORZALIGNED	   4043	   /* Horz. Aligned Radio Button	*/
#define	RB_RIGHTALIGNED	   4044	   /* Right Aligned Radio Button	*/
#define	RB_TOPALIGNED	   4045	   /* Top Aligned Radio	Button		*/
#define	RB_VERTCENTERED	   4046	   /* Vert. Centered Radio Button	*/
#define	RB_BOTALIGNED	   4047	   /* Bottom Aligned Radio Button	*/
#define	CB_WORDWRAP	   4048	   /* Word Wrap	Check Box		*/
#define	CB_HALFTONE	   4049	   /* Halftone Check Box		*/
#define	CB_MNEMONIC	   4050	   /* Mneumonic	Check Box		*/
#define	EF_TEXT		   4051	   /* Text Edit	Field			*/
#define	IDBX_SYMBOLVALUE   4053	   /* ID Value Edit Field		*/
#define	RB_RAISED	   4060	   /* Raised Text Radio	Button		*/
#define	RB_DEPRESSED	   4061	   /* Depressed	Text Radio Button	*/

/* --- Styles String ID's --------------------------------------------- */

#define	IDS_SS_TEXT	      0
#define	IDS_DT_LEFT	      1
#define	IDS_DT_CENTER	      2
#define	IDS_DT_RIGHT	      3
#define	IDS_DT_TOP	      4
#define	IDS_DT_VCENTER	      5
#define	IDS_DT_BOTTOM	      6
#define	IDS_DT_HALFTONE	      7
#define	IDS_DT_MNEMONIC	      8
#define	IDS_DT_WORDBREAK      9
#define	IDS_DS_RAISED	      10
#define	IDS_DS_DEPRESSED      11
